### ISSUE TITLE
Missing Start Script

### ISSUE THREAD

**Issue by Vulps22** [qShadxw/Discord-Bot-Template#1]
Really helpful template you got here

couple things, firstly you're missing a start script

Most developers will instinctively clone your project and type in `npm run start` instead of `node index.js`

also it would be helpful to have a blank copy of the `.env` file so that all we have to do is fill in the appropriate fields 😄

**Comment by qShadxw** [comment]
Thank you for bringing this up. I'll work on a commit now with the desired changes.

**Comment by qShadxw** [comment]
Added recommendations in newest commit. Thank you!
